[package]
name = "deadlocked"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
glam = "0.29"
libc = "0.2"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.26", features = ["derive"] }
toml = "0.8"

[profile.release]
lto = true
strip = "debuginfo"
