[package]
name = "deadlocked"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.14"
eframe = "0.29"
glam = "0.29"
strum = { version = "0.26", features = ["derive"] }
serde = {version = "1.0", features = ["derive"]}
toml = "0.8"
